const express=require('express'),Database=require('better-sqlite3'),crypto=require('crypto'),path=require('path'),fs=require('fs');
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'20kb'}));
const dir=process.env.DATA_DIR||path.join(__dirname,'data');fs.mkdirSync(dir,{recursive:true});const db=new Database(path.join(dir,'tickets.sqlite'));db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS people(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE,active INTEGER NOT NULL DEFAULT 1);CREATE TABLE IF NOT EXISTS restaurants(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE,active INTEGER NOT NULL DEFAULT 1);CREATE TABLE IF NOT EXISTS restaurant_usage(person_id INTEGER NOT NULL,restaurant_id INTEGER NOT NULL,day TEXT NOT NULL,count INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(person_id,restaurant_id,day));`);
const password=process.env.ADMIN_PASSWORD;if(!password){console.error('ADMIN_PASSWORD 환경변수를 설정하세요');process.exit(1)}const sessions=new Map(),attempts=new Map();
function admin(req,res,next){const t=(req.headers.authorization||'').replace(/^Bearer /,'');const exp=sessions.get(t);if(!exp||exp<Date.now()){sessions.delete(t);return res.status(401).json({error:'관리자 로그인이 필요합니다.'})}next()}
const today=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,10);const validMonth=s=>/^\d{4}-(0[1-9]|1[0-2])$/.test(s);const validId=n=>Number.isSafeInteger(n)&&n>0;
app.use(express.static(path.join(__dirname,'public')));
app.get('/api/people',(req,res)=>res.json(db.prepare('SELECT id,name FROM people WHERE active=1 ORDER BY name').all()));
app.get('/api/restaurants',(req,res)=>res.json(db.prepare('SELECT id,name FROM restaurants WHERE active=1 ORDER BY name').all()));
app.get('/api/usage',(req,res)=>{const id=Number(req.query.person),month=String(req.query.month||today().slice(0,7));if(!validId(id)||!validMonth(month))return res.status(400).json({error:'조회 조건 오류'});res.json(db.prepare('SELECT restaurant_id, SUM(count) count FROM restaurant_usage WHERE person_id=? AND day LIKE ? GROUP BY restaurant_id').all(id,month+'-%'))});
const change=db.transaction((p,r,delta)=>{if(!db.prepare('SELECT id FROM people WHERE id=? AND active=1').get(p)||!db.prepare('SELECT id FROM restaurants WHERE id=? AND active=1').get(r))throw Error('직원 또는 식당을 확인하세요.');const day=today();const old=db.prepare('SELECT count FROM restaurant_usage WHERE person_id=? AND restaurant_id=? AND day=?').get(p,r,day)?.count||0;const next=old+delta;if(next<0||next>999)throw Error('하루 0~999장까지 입력할 수 있습니다.');db.prepare('INSERT INTO restaurant_usage(person_id,restaurant_id,day,count) VALUES(?,?,?,?) ON CONFLICT(person_id,restaurant_id,day) DO UPDATE SET count=excluded.count').run(p,r,day,next);return next});
app.post('/api/click',(req,res)=>{const p=Number(req.body?.person),r=Number(req.body?.restaurant),delta=req.body?.delta;if(!validId(p)||!validId(r)||![-1,1].includes(delta))return res.status(400).json({error:'입력값 오류'});try{res.json({todayCount:change(p,r,delta)})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/admin/login',(req,res)=>{const ip=req.ip,a=attempts.get(ip)||{count:0,until:0};if(a.until>Date.now())return res.status(429).json({error:'15분 후 다시 시도하세요.'});const x=crypto.createHash('sha256').update(String(req.body?.password||'')).digest(),y=crypto.createHash('sha256').update(password).digest();if(!crypto.timingSafeEqual(x,y)){a.count++;if(a.count>=5){a.count=0;a.until=Date.now()+900000}attempts.set(ip,a);return res.status(401).json({error:'비밀번호가 틀렸습니다.'})}attempts.delete(ip);const token=crypto.randomBytes(32).toString('hex');sessions.set(token,Date.now()+43200000);res.json({token})});
app.post('/api/admin/logout',admin,(req,res)=>{sessions.delete((req.headers.authorization||'').replace(/^Bearer /,''));res.json({ok:true})});
for(const [route,table] of [['people','people'],['restaurants','restaurants']]){
app.get('/api/admin/'+route,admin,(req,res)=>res.json(db.prepare(`SELECT id,name,active FROM ${table} ORDER BY name`).all()));
app.post('/api/admin/'+route,admin,(req,res)=>{const name=String(req.body?.name||'').trim();if(!name||name.length>80)return res.status(400).json({error:'이름을 1~80자로 입력하세요.'});const old=db.prepare(`SELECT id FROM ${table} WHERE name=?`).get(name);if(old)db.prepare(`UPDATE ${table} SET active=1 WHERE id=?`).run(old.id);else db.prepare(`INSERT INTO ${table}(name) VALUES(?)`).run(name);res.json({ok:true})});
app.patch('/api/admin/'+route+'/:id',admin,(req,res)=>{const id=Number(req.params.id);if(!validId(id)||typeof req.body?.active!=='boolean')return res.status(400).json({error:'입력 오류'});db.prepare(`UPDATE ${table} SET active=? WHERE id=?`).run(req.body.active?1:0,id);res.json({ok:true})});
}
app.get('/api/admin/report',admin,(req,res)=>{const month=String(req.query.month||today().slice(0,7));if(!validMonth(month))return res.status(400).json({error:'월 형식 오류'});res.json(db.prepare('SELECT p.name person,r.name restaurant,u.day,u.count FROM restaurant_usage u JOIN people p ON p.id=u.person_id JOIN restaurants r ON r.id=u.restaurant_id WHERE u.day LIKE ? AND u.count>0 ORDER BY p.name,r.name,u.day').all(month+'-%'))});
app.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('식권 서버 실행 중'));
